#Une autre possibilite pour les web servers, pour le deploiement de site dapplications
FROM php:7.2-apache
COPY . /var/www/html/
#docker build -t gestionuser-angular:v1 .
#docker run -p 8081:80 -d gestionuser-angular:v1
#docker exec -it c4da /bin/bash
#ls
#http://localhost:8081/projects/angularProjects/gestionusers/allusers.php
#http://localhost:8081/projects/angularProjects/gestionusers/allusers.php?id=1
#http://localhost:8081/projects/angularProjects/gestionusers/allusers.php?id=2
#http://localhost:8081/projects/angularProjects/gestionusers/allusers.php?id=3