#Une autre possibilite pour les web servers, pour le deploiement de site web
FROM php:7.2-apache
COPY . /var/www/html/
#docker build -t gestionuser-php:v1 .
#docker run -p 80:80 -d gestionuser-php:v1
#docker ps
#http://localhost:80/gestionusers/allusers.php
