version: '3'

services:
  front:
    image: front-angular-animal:0.0.1
    container_name: container-front-angular-animal
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 82:80
